### ISSUE TITLE
Request: More tools for working with usernames

### ISSUE THREAD

**Issue by wsturgiss** [regisb/slack-cli#11]
<img width="402" alt="screen shot 2018-12-19 at 12 22 02 pm" src="https://user-images.githubusercontent.com/22747283/50236562-bba37c80-0388-11e9-819e-94f0f61ef125.png">

**Comment by wsturgiss** [comment]
Not a "bug" per se, but more of a feature request.

**Comment by wsturgiss** [comment]
When a user is tagged using @, and the message appears in the stream, it doesn't show the username, but instead shows an odd code

**Comment by wsturgiss** [comment]
Another request: some way to get a list of users that I have existing conversations with, or better yet some kind of tab completion when typing a users name.  If a user changes their username or I know vaguely what their username is, I end up needing to go to the slack app to find out their username so I can use it in the CLI

**Comment by regisb** [comment]
Hi @wsturgiss! Thanks for taking the time to open these issues. If you don't mind, I'll address the first question first, which is correctly printing usernames. This is indeed a bug.

As for user/channel/group name tab-completion, I'll have to think about it. I think it would be a cool feature, but it needs some work.

**Comment by regisb** [comment]
Fixed in the latest release. Previous output was:

    hello this is <@USLACKBOT> talking in <#C02SNA1U4|general>

Now:

    hello this is <@slackbot> talking in <#general>

Thanks for raising this issue!

**Comment by wsturgiss** [comment]
Thanks! That tagging issue fix works like a charm.
