### ISSUE TITLE
Multiline bot messages are truncated to first line only. 

### ISSUE THREAD

**Issue by jayharrison-okta** [regisb/slack-cli#17]
For example `$ slack-cli -t $(cat .slack-token) -s my-alerts -l 5`
gives:
```
[@my-alerts 2019-01-16 11:13:47] PagerDuty:
[@my-alerts 2019-01-16 12:13:46] Zabbix VPC:
[@my-alerts 2019-01-16 12:33:22] Zabbix VPC:
[@my-alerts 2019-01-16 12:37:39] PagerDuty:
[@my-alerts 2019-01-16 12:37:51] PagerDuty:
```
when the channel is showing: 
![screen shot 2019-01-16 at 12 54 27](https://user-images.githubusercontent.com/41923606/51250469-6447fa80-198e-11e9-974d-95efeda97ffc.png)

Any way to get multiline messages to be retrieved too?

**Comment by regisb** [comment]
Good catch! Can you try the latest release, see if it works for you? (v2.2.3)
