### ISSUE TITLE
Searching old timestamp slack message

### ISSUE THREAD

**Issue by GitAvinashreddy** [regisb/slack-cli#2]
Firstly I would like to thank for sharing this. 

I would be great if you could elaborate the reading/monitoring feature. cause we are not getting any output with the below command. 

slack-cli -s slackbot -

I need to constantly monitor a particular channel is it possible. Is it possible to search the data for specific time-stamp.

**Comment by regisb** [comment]
Hi! Sorry for the late response, I've been away from the Internet for about two weeks.

Have you tried without the terminal dash?

    slack-cli -s slackbot

Could you specify what kind of output you would like to obtain by searching for a specific timestamp? What you are trying to obtain is not very clear to me.

**Comment by GitAvinashreddy** [comment]
Hello There,

Thanks for replying, Its actually festival season here in India, So was
unable to reply.

Actually in my organization we have a channel which auto send's message
from the server via incoming-webhook app.

As a client we want to read the content of the particular channel and save
it on client machine.

Do let me know your name. I am Avinash.

**Comment by regisb** [comment]
Hi Avinash! I'm Régis.
I think I understand: you need not only to stream the content of the channel, (`slack-cli -s mychannel > mychannel.log`) but also to dump the archives of that channel since a certain timestamp. Right?
It shouldn't be too hard to do. The trick is to come up with the right CLI flag. I'll try to think of something.

**Comment by regisb** [comment]
@GitAvinashreddy I implemented a feature which might solve your problem:

    slack-cli -s yourchannel --last 10000

Should print the last 10000 messages from your channel. Just redirect to a file to backup the content of the channel.

If this does not solve your problem, feel free to re-open this issue.
