### ISSUE TITLE
unbuffered stdout / flush print?

### ISSUE THREAD

**Issue by qtfkwk** [regisb/slack-cli#22]
Realized while trying to use `slack-cli -s all` inside a script the prints weren't flushed immediately (presumably due to buffering?).

Adding `-u` to the python shebang in the generated console script shim worked.

Did not try, but the following in `slackcli/stream.py` should work and be portable across Python 2 and 3:

```
import sys

...

            print(utils.format_message(source_name, data))
            sys.stdout.flush()
```

Personally I finally settled with using `print(..., flush=True)` and that is working for me.

```
diff --git a/slackcli/stream.py b/slackcli/stream.pyindex 9d90e21..97f2368 100644
--- a/slackcli/stream.py
+++ b/slackcli/stream.py
@@ -33,4 +33,4 @@ def loop(sources):
                 # The streaming API provides all messages in all channels, so
                 # we need to do some filtering here
                 continue
-            print(utils.format_message(source_name, data))
+            print(utils.format_message(source_name, data), flush=True)
```

Your call whether to apply and the best approach!

**Comment by regisb** [comment]
Hi @qtfkwk, thanks for your suggestions!

> Adding -u to the python shebang in the generated console script shim worked.

What exactly do you mean by that?

**Comment by regisb** [comment]
@qtfkwk I don't really understand what you mean when you say you are running `slack-cli` from "inside a script". Do you mean a bash/shell script? If so, you can solve your problem either by adding the `-u` option to the `python` command (as you mentioned) or define the `PYTHONUNBUFFERED=1` environment variable.

I'd prefer if users implemented these custom solutions themselves, as I don't want to tinker with the default buffering approach, which I assume is sane in most cases.

**Comment by qtfkwk** [comment]
All good.
