### ISSUE TITLE
Question/Feature Request: How do I update status?

### ISSUE THREAD

**Issue by chipbite** [regisb/slack-cli#26]
Hello!
I tried 
`slack-cli -d slackbot "/status :office: In Office"`

but it does not work. 
Any clues? Or does this require new development?

**Comment by nixfreak** [comment]
Works for me  /status 🏢 In Office

**Comment by chipbite** [comment]
Hi @nixfreak  - not sure what you mean.
First you write:
> Works for me /status 🏢 In Office
OK, so you got a different result than me? 

But, then you write:
> I can it back , no the status is not changed.
"no the status is not changed"  - what does that mean?

Sorry for not getting you.

**Comment by regisb** [comment]
Hi @chipbite @nixfreak! This should now work in the latest release (v2.2.6).

**Comment by chipbite** [comment]
Forgot to say: Thanks! 

It works really well. I've got my slack status commands set up so I can switch, good nowadays when working from home, I find.

Take care!
