### ISSUE TITLE
Is it possible to exclude channels when using -s all?

### ISSUE THREAD

**Issue by jbl-proglove** [regisb/slack-cli#27]
Hi there,

thanks for the nice cli!
I was wondering: is it possible to use the `-s` flag to exclude a channel?
I want to setup two windows, one running `slack-cli -s some-channel` and another one using `slack-cli -s all -s !some-channel`.

The `!some-channel` is just an example for a negation of course. I want to display everything but the stuff from `some-channel`.

Thanks in advance and cheers,

Julius

**Comment by regisb** [comment]
Hi @jbl-proglove! I think you can solve this problem by taking advantage of other unix tools. Would the following work for you?

    slack-cli -s all | grep --invert-match "@some-channel"

I'll close this issue now, feel free to reopen if you think the proposed solution does not properly address the problem.
