### ISSUE TITLE
Not able to receive messages from bots

### ISSUE THREAD

**Issue by donglaizhang** [regisb/slack-cli#29]
Hey,
thank you for creating this amazing tool. I am trying to use it to receive messages via:
```
slack-cli -s all
or 
slack-cli -s channel-name
```
`slack-cli` is able to receive messages from persons, but not from bots. I am not sure it is the intention. 

tested with option: `-l` below:  
```
slack-cli -s channel-name -l 100
```
all messages including from person and from bots are displayed in console.

Regards,
Donglai

**Comment by regisb** [comment]
Hi @donglaizhang! I'm not sure I understand what your problem is. 

> tested with option: -l below:
> 
> `slack-cli -s channel-name -l 100`
> 
> all messages including from person and from bots are displayed in console.

This is the expected behaviour, right?

Can you please paste here the exact command that you are running, the output that you are getting and why it's different from what you expected?

**Comment by regisb** [comment]
Closed from lack of feedback. Please comment here if you feel your issue was not addressed properly.
