### ISSUE TITLE
Checking token with group "general" breaks

### ISSUE THREAD

**Issue by MuhammadAlkarouri** [regisb/slack-cli#3]
Trying to run `slack-cli` to send a message breaks with the error below. I checked our slack community and it doesn't have a channel called `general`. Does it have to exist? The only reason it is used in the code as far as I can see is to check that the token works.

>  slack-cli -d muhammad.alkarouri -s muhammad.alkarouri hi
> Traceback (most recent call last):
>   File "/usr/local/bin/slack-cli", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/slackcli/slack.py", line 9, in main
>     sys.exit(run())
>   File "/usr/local/lib/python2.7/site-packages/slackcli/slack.py", line 20, in run
>     args, token = utils.parse_args(parser)
>   File "/usr/local/lib/python2.7/site-packages/slackcli/utils.py", line 31, in parse_args
>     get_source_id(token, "general")
>   File "/usr/local/lib/python2.7/site-packages/slackcli/utils.py", line 92, in get_source_id
>     raise ValueError(u"Channel, group or user '{}' does not exist".format(source_name))
> ValueError: Channel, group or user 'general' does not exist

**Comment by regisb** [comment]
Hi @MuhammadAlkarouri,

Thanks for taking the time to create this issue!

You are absolutely right: the call to `get_source_id(token, "general")` is only made to check the credentials. I naively thought that every team had a "general" channel, but I now realise this is not the case. I'll work on a fix to avoid relying on the general channel.

**Comment by regisb** [comment]
This issue was fixed in release 1.0.2. @MuhammadAlkarouri can you please confirm that upgrading to the latest release fixes the issue? If not, feel free to reopen this.

**Comment by MuhammadAlkarouri** [comment]
Sorry for the late response. Yes, it is fixed.
