### ISSUE TITLE
Error when config dir not writable

### ISSUE THREAD

**Issue by neilsf** [regisb/slack-cli#31]
Hi. Thanks for this great script.

While saving the API token to the user's home (in Linux at least) is a convenient feature, there can be situations where the current user can't write to the directory, e.g:

- User does not have a home (did not test this, maybe there's a fallback)
- User is impersonalized with sudo and thus cannot write the initiater's home directory

In such cases the script halts with an error. I would suggest to display a warning only and let the script continue. The script should be able to execute without saving the API token.

**Comment by regisb** [comment]
Hi @neilsf! This is addressed in v2.2.7. Please let me know if it works for you.

**Comment by neilsf** [comment]
I can't really check now, but thanks for the update anyway.
