### ISSUE TITLE
WARNING- Ability to generate tokens is going away in May 2020

### ISSUE THREAD

**Issue by ArcticSnowman** [regisb/slack-cli#32]
https://api.slack.com/legacy/custom-integrations/legacy-tokens

**Comment by loomsen** [comment]
Migration to a slack app is actually pretty easy. Create a new app, add following scopes:

![Selection_469](https://user-images.githubusercontent.com/302524/80713203-5e2e4c80-8af3-11ea-9030-8aadc816e14a.png)

and use the generated oauth token for authentication. 

![Selection_470](https://user-images.githubusercontent.com/302524/80713358-9afa4380-8af3-11ea-8f6c-659c04c2bc16.png)

**Comment by regisb** [comment]
Thanks for the instructions @loomsen! I just wanted to say that this issue is on my todo-list, but I'm currently kept busy by other projects.

**Comment by loomsen** [comment]
@regisb I can create a PR for the README if I find some time during the weekend or next week, no prob.

**Comment by regisb** [comment]
That would be great @loomsen.

**Comment by loomsen** [comment]
Please review @regisb @ArcticSnowman
