### ISSUE TITLE
Error message is cryptic on missing channel

### ISSUE THREAD

**Issue by regisb** [regisb/slack-cli#4]
```
$ slack-cli -d pouacpouac test
Traceback (most recent call last):
  File "/home/data/regis/projets/code/slack-cli/env/bin/slack-cli", line 11, in <module>
    load_entry_point('slack-cli', 'console_scripts', 'slack-cli')()
  File "/home/data/regis/projets/code/slack-cli/slackcli/cli.py", line 10, in main
    sys.exit(run())
  File "/home/data/regis/projets/code/slack-cli/slackcli/cli.py", line 65, in run
    send_message(args.dst, message, pre=args.pre)
  File "/home/data/regis/projets/code/slack-cli/slackcli/cli.py", line 105, in send_message
    destination_id = utils.get_source_id(destination)
  File "/home/data/regis/projets/code/slack-cli/slackcli/utils.py", line 43, in get_source_id
    raise ValueError(u"Channel, group or user '{}' does not exist".format(source_name))
ValueError: Channel, group or user 'pouacpouac' does not exist
```

We would expect the program to fail more gracefully.

**Comment by sommern** [comment]
This issue only scratches the surface of the need for exception handling. It also needs to fail gracefully if the team does not exist, the token is invalid, there is an error communicating with the slack server, there is an error writing to disk, etc.

**Comment by regisb** [comment]
Hi @sommern, thanks for taking the time to comment on this! 

> if the team does not exist

In that case, `slack-cli` assumes that the team's token was not created, so it asks the user for the team's token. After the user gives his token, the token is verified ; since the team does not exist, the token verification will fail. I don't really see a better way to check for team existence.

> the token is invalid

When the token is invalid, the user receives a clean "Invalid slack token" error.

> there is an error communicating with the slack server, there is an error writing to disk, etc.

I like to think that the end-user is a developer who doesn't mind receiving a stacktrace on "low level" errors that should not happen that often. This makes it much easier to debug, after eventually opening a new ticket here.

I improved exception handling in case of incorrect channel name. Please feel free to re-open this ticket if you feel my comments and commit did not address your concerns.
