### ISSUE TITLE
Receive/download files

### ISSUE THREAD

**Issue by au-phiware** [regisb/slack-cli#9]
Is it possible to download a file/snippet that is attached to a message. Messages with a file appear to be empty, e.g.

```
$ slack-cli -s au-phiware -l 1
[@au-phiware 2018-12-07 16:59:35] au-phiware: 
$ 
```

Perhaps something like this:

```
$ slack-cli -s au-phiware -l 1 -o /dev/stdout
[@au-phiware 2018-12-07 16:59:35] au-phiware:
This is a test
plain text file that was uploaded to slack!
$ 
```

**Comment by regisb** [comment]
What do you think of the proposed solution? It will print file uploads like this:

```
[@slackbot 2018-12-07 15:53:36] regis: This is a message associated to a file upload!
    depressed.png: https://files.slack.com/files-pri/T02SNA1T6-FENE8E89K/depressed.png
```

**Comment by au-phiware** [comment]
I can see how that would be useful if there were many files in the selected messages, but I would still like some way to get it on to the stdout.
